name: azure-container-image-scan

on:
  push:
  pull_request:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
 build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      env:
          # (Required) The token to use to make API calls to GitHub.
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-besu-all-in-one
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-whitepaper
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-cmd-api-server
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-connector-fabric
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-connector-corda-server
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-connector-besu
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: corda-4-6-all-in-one-obligation
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-corda-4-7-all-in-one-obligation
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: corda-4-8-all-in-one-obligation-publish
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-dev-container-vscode
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-example-carbon-accounting
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-example-supply-chain-app
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-fabric-all-in-one
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-fabric2-all-in-one
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-iroha-all-in-one
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-keychain-vault-server
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-quorum-all-in-one
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-rust-compiler
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - uses: Azure/container-scan@v0.1
    #   with:
    #     image-name: cactus-test-npm-registry
    #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin