name: Container-image-scan

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
 build-secure-and-push:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.4.0
    - name: Build image
      run: docker build $DOCKER_BUILD_DIR --file $DOCKERFILE_PATH --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Login to DockerHub Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-besu-all-in-one

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-whitepaper

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-cmd-api-server

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-connector-fabric

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-connector-corda-server

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-connector-besu

    - uses: Azure/container-scan@v0.1
      with:
        image-name: corda-4-6-all-in-one-obligation

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-corda-4-7-all-in-one-obligation

    - uses: Azure/container-scan@v0.1
      with:
        image-name: corda-4-8-all-in-one-obligation-publish
    
    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-dev-container-vscode

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-example-carbon-accounting

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-example-supply-chain-app

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-fabric-all-in-one

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-fabric2-all-in-one

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-iroha-all-in-one

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-keychain-vault-server

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-quorum-all-in-one

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-rust-compiler

    - uses: Azure/container-scan@v0.1
      with:
        image-name: cactus-test-npm-registry
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        #severity-threshold: # optional, default is HIGH
        # Username to authenticate to the Docker registry
        #username: # optional
        # Password to authenticate to the Docker registry
        #password: # optional
        # Github token
        #token: # default is ${{ github.token }}
        # Add additional checks to ensure the image is secure and follows best practices and CIS standards
        #run-quality-checks: # optional, default is true
