# Below are the full description for the shorten job names:
#
# ce - cactus-example
# cp - cactus-plugin
# cpk - cactus-plugin-keychain
# cpl - cactus-plugin-ledger
# cplc - cactus-plugin-ledger-connector
# plc - plugin-ledger-connector
# cpp - cactus-plugin-persistence
# ct - cactus-test
# ctp - cactus-test-plugin
---
env:
  NODEJS_VERSION: v18.18.2
  RUN_TRIVY_SCAN: true 
  PR_BODY: ${{ github.event.pull_request.body }}
  BEFORE_REF: ${{ github.event.before }}
  AFTER_REF: ${{ github.event.after }}
 
jobs:
  PR-desc-and-commit-msg-checker:
    runs-on: ubuntu-22.04
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Get PR description
        run: |
          echo "PR desc: ${PR_BODY}"
 
      - name: Get branch commit messages
        id: get_branch_commit_messages
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | grep -oP '\d+$')
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits"
          COMMIT_MESSAGES=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${API_URL}" | jq -r '.[].commit.message')
          echo "$COMMIT_MESSAGES" > branch_commit_messages.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Print branch commit messages
        run: |
          echo "Commit messages:"
          cat branch_commit_messages.txt

      - name: Compare PR Description and Commit Messages
        id: compare
        run: |
          ESCAPED_COMMIT_MESSAGES=$(echo "$COMMIT_MESSAGES" | sed 's/[][\.*^$(){}?+|]/\\&/g')

          if echo "$PR_DESCRIPTION" | grep -qF "$ESCAPED_COMMIT_MESSAGES"; then
            echo "PR description matches commit messages."
          else
            echo "PR description does not match commit messages."
            exit 1
          fi

name: Cactus_CI
'on':
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
      - dev
      - petermetz/**
  push:
    branches:
      - main
      - dev