# Below are the full description for the shorten job names:
#
# ce - cactus-example
# cp - cactus-plugin
# cpk - cactus-plugin-keychain
# cpl - cactus-plugin-ledger
# cplc - cactus-plugin-ledger-connector
# plc - plugin-ledger-connector
# cpp - cactus-plugin-persistence
# ct - cactus-test
# ctp - cactus-test-plugin
---
env:
  NODEJS_VERSION: v18.18.2
  RUN_TRIVY_SCAN: true 
  PR_BODY: ${{ github.event.pull_request.body }}
  BEFORE_REF: ${{ github.event.before }}
  AFTER_REF: ${{ github.event.after }}
 
jobs:
  PR-desc-and-commit-msg-checker:
    runs-on: ubuntu-22.04
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: View issue information
        run: |
          echo "PR desc: ${PR_BODY}"
 
      - name: Get branch commit messages
        id: get_branch_commit_messages
        run: |
          branch_name=${{ github.head_ref }}
          repo_full_name=${{ github.repository }}
          commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$repo_full_name/commits?sha=$branch_name)
          commit_messages=$(echo "$commits" | jq -r '.[0].commit.message')
          echo "$commit_messages" > branch_commit_messages.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Print branch commit messages
        run: |
          echo "Commit messages from the branch ${{ github.head_ref }}:"
          cat branch_commit_messages.txt
name: Cactus_CI
'on':
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
      - dev
      - petermetz/**
  push:
    branches:
      - main
      - dev