# Below are the full description for the shorten job names:
#
# ce - cactus-example
# cp - cactus-plugin
# cpk - cactus-plugin-keychain
# cpl - cactus-plugin-ledger
# cplc - cactus-plugin-ledger-connector
# plc - plugin-ledger-connector
# cpp - cactus-plugin-persistence
# ct - cactus-test
# ctp - cactus-test-plugin
---
env:
  NODEJS_VERSION: v18.18.2
  RUN_TRIVY_SCAN: true 
  PR_BODY: ${{ github.event.pull_request.body }}
  BEFORE_REF: ${{ github.event.before }}
  AFTER_REF: ${{ github.event.after }}
  #COMMIT_MSG: ${{ github.event.pull_request.base.sha }}
jobs:
  check_pr_description_and_commit_message:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: Fetch PR Details
        id: fetch_pr_details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
 
      - name: Fetch Commit Messages
        id: fetch_commit_messages
        run: |
          commits=$(gh pr view ${{ github.event.number }} --json commits --jq '.commits')
          echo "::set-output name=commits::${commits}"
        continue-on-error: true
 
      - name: Compare PR Description and Commit Messages
        id: compare
        run: |
          pr_body="${{ steps.fetch_pr_details.outputs.data.body }}"
          commit_messages="${{ steps.fetch_commit_messages.outputs.commits }}"
 
          if [[ -z "$pr_body" || -z "$commit_messages" ]]; then
            echo "Error fetching PR details or commit messages"
            exit 1
          fi
 
          mismatch=false
 
          for message in $commit_messages; do
            if [[ ! "$pr_body" == *"$message"* ]]; then
              mismatch=true
              break
            fi
          done
 
          echo "mismatch=$mismatch" >> $GITHUB_ENV
 
      - name: Fail if Mismatch Found
        if: env.mismatch == 'true'
        run: |
          echo "Commit messages do not match PR description"
          exit 1
name: Cactus_CI
'on':
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
      - dev
      - petermetz/**
  push:
    branches:
      - main
      - dev