# Below are the full description for the shorten job names:
#
# ce - cactus-example
# cp - cactus-plugin
# cpk - cactus-plugin-keychain
# cpl - cactus-plugin-ledger
# cplc - cactus-plugin-ledger-connector
# plc - plugin-ledger-connector
# cpp - cactus-plugin-persistence
# ct - cactus-test
# ctp - cactus-test-plugin
---
env:
  NODEJS_VERSION: v18.18.2
  RUN_TRIVY_SCAN: true 
  PR_BODY: ${{ github.event.pull_request.body }}
  BEFORE_REF: ${{ github.event.before }}
  AFTER_REF: ${{ github.event.after }}
 
jobs:
  PR-desc-and-commit-msg-checker:
    runs-on: ubuntu-22.04
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: View issue information
        run: |
          echo "PR desc: ${PR_BODY}"
 
      - name: Get branch commit messages
        id: get_branch_commit_messages
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | cut -d'/' -f7)
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits"
          COMMIT_MESSAGES=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" $API_URL | jq -r '.[].commit.message')
          echo "::set-output name=commit_messages::${COMMIT_MESSAGES}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Print branch commit messages
        run: |
          run: echo "${{ steps.get_commit_messages.outputs.commit_messages }}"
name: Cactus_CI
'on':
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
      - dev
      - petermetz/**
  push:
    branches:
      - main
      - dev